# Generated by Django 6.0.3 on 2026-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_currency_job_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
