services:
  web:
    build: .
    command: sh -c "sh migrate.sh && gunicorn fsm_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - db
      - minio
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-?Hixi3USasp$$}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A fsm_backend worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - db
      - minio
      - redis

  test_runner:
    build: .
    command: sh test.sh
    profiles:
      - testing
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - db
      - minio
      - redis

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-minioadmin}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres_data:
  minio_data:
  redis_data:
