# Generated by Django 6.0.3 on 2026-03-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('technician', 'Technician'), ('driver', 'Driver'), ('inspectors', 'Inspectors')], default='technician', max_length=50),
        ),
    ]
